### ISSUE TITLE
Update for Laravel 5

### ISSUE THREAD

**Issue by tucq88** [antonioribeiro/laravelcs#10]
As Laravel 5 using PSR-2 , this package is out-of-date.

**Comment by lawrencegs** [comment]
@tucq88 - have you found a different solution? seems like the project owner @antonioribeiro haven't been around for a while.

**Comment by tucq88** [comment]
@lawrencegs I don't see this project benefit anymore, only CodeSniffer is not enough, that's why I created new project to integrate other tools with Laravel 
https://github.com/tucq88/jenkins-laravel
